### ISSUE TITLE
wew

### ISSUE THREAD

**Issue by khongyew** [teamcsp/fml#1]
https://github.com/teamcsp/fml/blob/b7324d3ed586f144dc6c630e904d32fa429e71d3/simple_client_server_attacker.csp#L201-L206

eh boss @QzSG . i think in attacker as server, need change some '!' to '?'.

**Comment by QzSG** [comment]
Eh why leh

**Comment by QzSG** [comment]
If attacker detects client hello, it buffers (adds to buffer channel), since hello will definitely come with client key share wait for it from client and add to buffer also?

**Comment by QzSG** [comment]
Oh wait
